/* GENERATED by process_pieces.py — do not edit by hand. */
const PIECES_DATA = {
 "plant": {
  "title": "Blooms",
  "rules": [
   "element",
   "position"
  ],
  "pool": {
   "element": [
    {
     "value": "water",
     "imgs": [
      "assets/game/plant-water-1.png",
      "assets/game/plant-water-2.png"
     ],
     "timgs": [
      "assets/game/pest-bee-1.png",
      "assets/game/pest-bee-2.png",
      "assets/game/pest-bee-3.png",
      "assets/game/pest-bee-4.png",
      "assets/game/pest-bee-5.png",
      "assets/game/pest-bee-6.png"
     ],
     "color": "#3fa9f5"
    },
    {
     "value": "light",
     "imgs": [
      "assets/game/plant-light-1.png",
      "assets/game/plant-light-2.png"
     ],
     "timgs": [
      "assets/game/pest-snail.png"
     ],
     "color": "#ffd75e"
    },
    {
     "value": "fire",
     "imgs": [
      "assets/game/plant-fire-1.png",
      "assets/game/plant-fire-2.png"
     ],
     "timgs": [
      "assets/game/pest-fly-1.png",
      "assets/game/pest-fly-2.png"
     ],
     "color": "#ff6b4a"
    },
    {
     "value": "wind",
     "imgs": [
      "assets/game/plant-wind-1.png",
      "assets/game/plant-wind-2.png"
     ],
     "timgs": [
      "assets/game/pest-spider.png"
     ],
     "color": "#7ee081"
    },
    {
     "value": "earth",
     "imgs": [
      "assets/game/plant-earth-1.png",
      "assets/game/plant-earth-2.png"
     ],
     "timgs": [
      "assets/game/pest-orange-spider.png"
     ],
     "color": "#c98a4b"
    },
    {
     "value": "frost",
     "imgs": [
      "assets/game/plant-frost-1.png",
      "assets/game/plant-frost-2.png"
     ],
     "timgs": [
      "assets/game/pest-slug.png"
     ],
     "color": "#9be8ff"
    }
   ],
   "position": [
    {
     "value": 0,
     "imgs": [
      "assets/game/plant-water-1.png",
      "assets/game/plant-water-2.png"
     ],
     "timgs": [
      "assets/game/pest-bee-1.png",
      "assets/game/pest-bee-2.png",
      "assets/game/pest-bee-3.png",
      "assets/game/pest-bee-4.png",
      "assets/game/pest-bee-5.png",
      "assets/game/pest-bee-6.png"
     ],
     "color": "#3fa9f5"
    },
    {
     "value": 1,
     "imgs": [
      "assets/game/plant-light-1.png",
      "assets/game/plant-light-2.png"
     ],
     "timgs": [
      "assets/game/pest-snail.png"
     ],
     "color": "#ffd75e"
    },
    {
     "value": 2,
     "imgs": [
      "assets/game/plant-fire-1.png",
      "assets/game/plant-fire-2.png"
     ],
     "timgs": [
      "assets/game/pest-fly-1.png",
      "assets/game/pest-fly-2.png"
     ],
     "color": "#ff6b4a"
    },
    {
     "value": 3,
     "imgs": [
      "assets/game/plant-wind-1.png",
      "assets/game/plant-wind-2.png"
     ],
     "timgs": [
      "assets/game/pest-spider.png"
     ],
     "color": "#7ee081"
    },
    {
     "value": 4,
     "imgs": [
      "assets/game/plant-earth-1.png",
      "assets/game/plant-earth-2.png"
     ],
     "timgs": [
      "assets/game/pest-orange-spider.png"
     ],
     "color": "#c98a4b"
    },
    {
     "value": 5,
     "imgs": [
      "assets/game/plant-frost-1.png",
      "assets/game/plant-frost-2.png"
     ],
     "timgs": [
      "assets/game/pest-slug.png"
     ],
     "color": "#9be8ff"
    }
   ]
  }
 },
 "fruit": {
  "title": "Fruits",
  "rules": [
   "color",
   "type",
   "position"
  ],
  "pool": {
   "color": [
    {
     "value": "red",
     "imgs": [
      "assets/game/pieces/fruit/fruit_apple.png",
      "assets/game/pieces/fruit/fruit_cherries.png",
      "assets/game/pieces/fruit/fruit_strawberry.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_apple.png",
      "assets/game/pieces/fruit/fruit_cherries.png",
      "assets/game/pieces/fruit/fruit_strawberry.png"
     ],
     "color": "#e0393e"
    },
    {
     "value": "yellow",
     "imgs": [
      "assets/game/pieces/fruit/fruit_banana.png",
      "assets/game/pieces/fruit/fruit_lemon.png",
      "assets/game/pieces/fruit/fruit_pineapple_01.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_banana.png",
      "assets/game/pieces/fruit/fruit_lemon.png",
      "assets/game/pieces/fruit/fruit_pineapple_01.png"
     ],
     "color": "#f6c915"
    },
    {
     "value": "purple",
     "imgs": [
      "assets/game/pieces/fruit/fruit_blackberries.png",
      "assets/game/pieces/fruit/fruit_grapes.png",
      "assets/game/pieces/fruit/fruit_plum.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_blackberries.png",
      "assets/game/pieces/fruit/fruit_grapes.png",
      "assets/game/pieces/fruit/fruit_plum.png"
     ],
     "color": "#8e5bd6"
    },
    {
     "value": "blue",
     "imgs": [
      "assets/game/pieces/fruit/fruit_blueberries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_blueberries.png"
     ],
     "color": "#2f7fe8"
    },
    {
     "value": "brown",
     "imgs": [
      "assets/game/pieces/fruit/fruit_coconut_01.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_coconut_01.png"
     ],
     "color": "#8d6e63"
    },
    {
     "value": "green",
     "imgs": [
      "assets/game/pieces/fruit/fruit_kiwi.png",
      "assets/game/pieces/fruit/fruit_olive.png",
      "assets/game/pieces/fruit/fruit_pear.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_kiwi.png",
      "assets/game/pieces/fruit/fruit_olive.png",
      "assets/game/pieces/fruit/fruit_pear.png"
     ],
     "color": "#4caf50"
    },
    {
     "value": "orange",
     "imgs": [
      "assets/game/pieces/fruit/fruit_orange.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_orange.png"
     ],
     "color": "#f28a1e"
    },
    {
     "value": "pink",
     "imgs": [
      "assets/game/pieces/fruit/fruit_raspberries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_raspberries.png"
     ],
     "color": "#e26ab0"
    }
   ],
   "type": [
    {
     "value": "apple",
     "imgs": [
      "assets/game/pieces/fruit/fruit_apple.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_apple.png"
     ],
     "color": "#e0393e"
    },
    {
     "value": "banana",
     "imgs": [
      "assets/game/pieces/fruit/fruit_banana.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_banana.png"
     ],
     "color": "#f6c915"
    },
    {
     "value": "blackberries",
     "imgs": [
      "assets/game/pieces/fruit/fruit_blackberries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_blackberries.png"
     ],
     "color": "#8e5bd6"
    },
    {
     "value": "blueberries",
     "imgs": [
      "assets/game/pieces/fruit/fruit_blueberries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_blueberries.png"
     ],
     "color": "#2f7fe8"
    },
    {
     "value": "cherries",
     "imgs": [
      "assets/game/pieces/fruit/fruit_cherries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_cherries.png"
     ],
     "color": "#e0393e"
    },
    {
     "value": "coconut_01",
     "imgs": [
      "assets/game/pieces/fruit/fruit_coconut_01.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_coconut_01.png"
     ],
     "color": "#8d6e63"
    },
    {
     "value": "grapes",
     "imgs": [
      "assets/game/pieces/fruit/fruit_grapes.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_grapes.png"
     ],
     "color": "#8e5bd6"
    },
    {
     "value": "kiwi",
     "imgs": [
      "assets/game/pieces/fruit/fruit_kiwi.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_kiwi.png"
     ],
     "color": "#4caf50"
    },
    {
     "value": "lemon",
     "imgs": [
      "assets/game/pieces/fruit/fruit_lemon.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_lemon.png"
     ],
     "color": "#f6c915"
    },
    {
     "value": "olive",
     "imgs": [
      "assets/game/pieces/fruit/fruit_olive.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_olive.png"
     ],
     "color": "#4caf50"
    },
    {
     "value": "orange",
     "imgs": [
      "assets/game/pieces/fruit/fruit_orange.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_orange.png"
     ],
     "color": "#f28a1e"
    },
    {
     "value": "pear",
     "imgs": [
      "assets/game/pieces/fruit/fruit_pear.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_pear.png"
     ],
     "color": "#4caf50"
    },
    {
     "value": "pineapple_01",
     "imgs": [
      "assets/game/pieces/fruit/fruit_pineapple_01.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_pineapple_01.png"
     ],
     "color": "#f6c915"
    },
    {
     "value": "plum",
     "imgs": [
      "assets/game/pieces/fruit/fruit_plum.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_plum.png"
     ],
     "color": "#8e5bd6"
    },
    {
     "value": "raspberries",
     "imgs": [
      "assets/game/pieces/fruit/fruit_raspberries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_raspberries.png"
     ],
     "color": "#e26ab0"
    },
    {
     "value": "strawberry",
     "imgs": [
      "assets/game/pieces/fruit/fruit_strawberry.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_strawberry.png"
     ],
     "color": "#e0393e"
    }
   ],
   "position": [
    {
     "value": 0,
     "imgs": [
      "assets/game/pieces/fruit/fruit_apple.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_apple.png"
     ],
     "color": null
    },
    {
     "value": 1,
     "imgs": [
      "assets/game/pieces/fruit/fruit_banana.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_banana.png"
     ],
     "color": null
    },
    {
     "value": 2,
     "imgs": [
      "assets/game/pieces/fruit/fruit_blackberries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_blackberries.png"
     ],
     "color": null
    },
    {
     "value": 3,
     "imgs": [
      "assets/game/pieces/fruit/fruit_blueberries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_blueberries.png"
     ],
     "color": null
    },
    {
     "value": 4,
     "imgs": [
      "assets/game/pieces/fruit/fruit_cherries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_cherries.png"
     ],
     "color": null
    },
    {
     "value": 5,
     "imgs": [
      "assets/game/pieces/fruit/fruit_coconut_01.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_coconut_01.png"
     ],
     "color": null
    },
    {
     "value": 6,
     "imgs": [
      "assets/game/pieces/fruit/fruit_grapes.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_grapes.png"
     ],
     "color": null
    },
    {
     "value": 7,
     "imgs": [
      "assets/game/pieces/fruit/fruit_kiwi.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_kiwi.png"
     ],
     "color": null
    },
    {
     "value": 8,
     "imgs": [
      "assets/game/pieces/fruit/fruit_lemon.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_lemon.png"
     ],
     "color": null
    },
    {
     "value": 9,
     "imgs": [
      "assets/game/pieces/fruit/fruit_olive.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_olive.png"
     ],
     "color": null
    },
    {
     "value": 10,
     "imgs": [
      "assets/game/pieces/fruit/fruit_orange.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_orange.png"
     ],
     "color": null
    },
    {
     "value": 11,
     "imgs": [
      "assets/game/pieces/fruit/fruit_pear.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_pear.png"
     ],
     "color": null
    },
    {
     "value": 12,
     "imgs": [
      "assets/game/pieces/fruit/fruit_pineapple_01.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_pineapple_01.png"
     ],
     "color": null
    },
    {
     "value": 13,
     "imgs": [
      "assets/game/pieces/fruit/fruit_plum.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_plum.png"
     ],
     "color": null
    },
    {
     "value": 14,
     "imgs": [
      "assets/game/pieces/fruit/fruit_raspberries.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_raspberries.png"
     ],
     "color": null
    },
    {
     "value": 15,
     "imgs": [
      "assets/game/pieces/fruit/fruit_strawberry.png"
     ],
     "timgs": [
      "assets/game/pieces/fruit/fruit_strawberry.png"
     ],
     "color": null
    }
   ]
  }
 },
 "animal": {
  "title": "Creatures",
  "rules": [
   "type",
   "position"
  ],
  "pool": {
   "type": [
    {
     "value": "elephant",
     "imgs": [
      "assets/game/pieces/animal/animal_elephant.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_elephant.png"
     ],
     "color": null
    },
    {
     "value": "giraffe",
     "imgs": [
      "assets/game/pieces/animal/animal_giraffe.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_giraffe.png"
     ],
     "color": null
    },
    {
     "value": "hippo",
     "imgs": [
      "assets/game/pieces/animal/animal_hippo.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_hippo.png"
     ],
     "color": null
    },
    {
     "value": "monkey",
     "imgs": [
      "assets/game/pieces/animal/animal_monkey.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_monkey.png"
     ],
     "color": null
    },
    {
     "value": "panda",
     "imgs": [
      "assets/game/pieces/animal/animal_panda.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_panda.png"
     ],
     "color": null
    },
    {
     "value": "parrot",
     "imgs": [
      "assets/game/pieces/animal/animal_parrot.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_parrot.png"
     ],
     "color": null
    },
    {
     "value": "penguin",
     "imgs": [
      "assets/game/pieces/animal/animal_penguin.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_penguin.png"
     ],
     "color": null
    },
    {
     "value": "pig",
     "imgs": [
      "assets/game/pieces/animal/animal_pig.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_pig.png"
     ],
     "color": null
    },
    {
     "value": "rabbit",
     "imgs": [
      "assets/game/pieces/animal/animal_rabbit.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_rabbit.png"
     ],
     "color": null
    },
    {
     "value": "snake",
     "imgs": [
      "assets/game/pieces/animal/animal_snake.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_snake.png"
     ],
     "color": null
    }
   ],
   "position": [
    {
     "value": 0,
     "imgs": [
      "assets/game/pieces/animal/animal_elephant.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_elephant.png"
     ],
     "color": null
    },
    {
     "value": 1,
     "imgs": [
      "assets/game/pieces/animal/animal_giraffe.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_giraffe.png"
     ],
     "color": null
    },
    {
     "value": 2,
     "imgs": [
      "assets/game/pieces/animal/animal_hippo.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_hippo.png"
     ],
     "color": null
    },
    {
     "value": 3,
     "imgs": [
      "assets/game/pieces/animal/animal_monkey.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_monkey.png"
     ],
     "color": null
    },
    {
     "value": 4,
     "imgs": [
      "assets/game/pieces/animal/animal_panda.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_panda.png"
     ],
     "color": null
    },
    {
     "value": 5,
     "imgs": [
      "assets/game/pieces/animal/animal_parrot.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_parrot.png"
     ],
     "color": null
    },
    {
     "value": 6,
     "imgs": [
      "assets/game/pieces/animal/animal_penguin.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_penguin.png"
     ],
     "color": null
    },
    {
     "value": 7,
     "imgs": [
      "assets/game/pieces/animal/animal_pig.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_pig.png"
     ],
     "color": null
    },
    {
     "value": 8,
     "imgs": [
      "assets/game/pieces/animal/animal_rabbit.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_rabbit.png"
     ],
     "color": null
    },
    {
     "value": 9,
     "imgs": [
      "assets/game/pieces/animal/animal_snake.png"
     ],
     "timgs": [
      "assets/game/pieces/animal/animal_snake.png"
     ],
     "color": null
    }
   ]
  }
 },
 "gem": {
  "title": "Crystals",
  "rules": [
   "color",
   "position"
  ],
  "pool": {
   "color": [
    {
     "value": "black",
     "imgs": [
      "assets/game/pieces/gem/gem_black_04.png",
      "assets/game/pieces/gem/gem_black_05.png",
      "assets/game/pieces/gem/gem_black_06.png",
      "assets/game/pieces/gem/gem_black_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_black_04.png",
      "assets/game/pieces/gem/gem_black_05.png",
      "assets/game/pieces/gem/gem_black_06.png",
      "assets/game/pieces/gem/gem_black_07.png"
     ],
     "color": "#888888",
     "tintable": false
    },
    {
     "value": "blue",
     "imgs": [
      "assets/game/pieces/gem/gem_blue_04.png",
      "assets/game/pieces/gem/gem_blue_05.png",
      "assets/game/pieces/gem/gem_blue_06.png",
      "assets/game/pieces/gem/gem_blue_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_blue_04.png",
      "assets/game/pieces/gem/gem_blue_05.png",
      "assets/game/pieces/gem/gem_blue_06.png",
      "assets/game/pieces/gem/gem_blue_07.png"
     ],
     "color": "#2f7fe8",
     "tintable": false
    },
    {
     "value": "green",
     "imgs": [
      "assets/game/pieces/gem/gem_green_04.png",
      "assets/game/pieces/gem/gem_green_05.png",
      "assets/game/pieces/gem/gem_green_06.png",
      "assets/game/pieces/gem/gem_green_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_green_04.png",
      "assets/game/pieces/gem/gem_green_05.png",
      "assets/game/pieces/gem/gem_green_06.png",
      "assets/game/pieces/gem/gem_green_07.png"
     ],
     "color": "#4caf50",
     "tintable": false
    },
    {
     "value": "grey",
     "imgs": [
      "assets/game/pieces/gem/gem_grey_04.png",
      "assets/game/pieces/gem/gem_grey_05.png",
      "assets/game/pieces/gem/gem_grey_06.png",
      "assets/game/pieces/gem/gem_grey_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_grey_04.png",
      "assets/game/pieces/gem/gem_grey_05.png",
      "assets/game/pieces/gem/gem_grey_06.png",
      "assets/game/pieces/gem/gem_grey_07.png"
     ],
     "color": "#888888",
     "tintable": false
    },
    {
     "value": "orange",
     "imgs": [
      "assets/game/pieces/gem/gem_orange_04.png",
      "assets/game/pieces/gem/gem_orange_05.png",
      "assets/game/pieces/gem/gem_orange_06.png",
      "assets/game/pieces/gem/gem_orange_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_orange_04.png",
      "assets/game/pieces/gem/gem_orange_05.png",
      "assets/game/pieces/gem/gem_orange_06.png",
      "assets/game/pieces/gem/gem_orange_07.png"
     ],
     "color": "#f28a1e",
     "tintable": false
    },
    {
     "value": "pink",
     "imgs": [
      "assets/game/pieces/gem/gem_pink_04.png",
      "assets/game/pieces/gem/gem_pink_05.png",
      "assets/game/pieces/gem/gem_pink_06.png",
      "assets/game/pieces/gem/gem_pink_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_pink_04.png",
      "assets/game/pieces/gem/gem_pink_05.png",
      "assets/game/pieces/gem/gem_pink_06.png",
      "assets/game/pieces/gem/gem_pink_07.png"
     ],
     "color": "#e26ab0",
     "tintable": false
    },
    {
     "value": "red",
     "imgs": [
      "assets/game/pieces/gem/gem_red_04.png",
      "assets/game/pieces/gem/gem_red_05.png",
      "assets/game/pieces/gem/gem_red_06.png",
      "assets/game/pieces/gem/gem_red_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_red_04.png",
      "assets/game/pieces/gem/gem_red_05.png",
      "assets/game/pieces/gem/gem_red_06.png",
      "assets/game/pieces/gem/gem_red_07.png"
     ],
     "color": "#e0393e",
     "tintable": false
    },
    {
     "value": "yellow",
     "imgs": [
      "assets/game/pieces/gem/gem_yellow_04.png",
      "assets/game/pieces/gem/gem_yellow_05.png",
      "assets/game/pieces/gem/gem_yellow_06.png",
      "assets/game/pieces/gem/gem_yellow_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_yellow_04.png",
      "assets/game/pieces/gem/gem_yellow_05.png",
      "assets/game/pieces/gem/gem_yellow_06.png",
      "assets/game/pieces/gem/gem_yellow_07.png"
     ],
     "color": "#f6c915",
     "tintable": false
    }
   ],
   "position": [
    {
     "value": 0,
     "imgs": [
      "assets/game/pieces/gem/gem_black_04.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_black_04.png"
     ],
     "color": null
    },
    {
     "value": 1,
     "imgs": [
      "assets/game/pieces/gem/gem_black_05.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_black_05.png"
     ],
     "color": null
    },
    {
     "value": 2,
     "imgs": [
      "assets/game/pieces/gem/gem_black_06.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_black_06.png"
     ],
     "color": null
    },
    {
     "value": 3,
     "imgs": [
      "assets/game/pieces/gem/gem_black_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_black_07.png"
     ],
     "color": null
    },
    {
     "value": 4,
     "imgs": [
      "assets/game/pieces/gem/gem_blue_04.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_blue_04.png"
     ],
     "color": null
    },
    {
     "value": 5,
     "imgs": [
      "assets/game/pieces/gem/gem_blue_05.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_blue_05.png"
     ],
     "color": null
    },
    {
     "value": 6,
     "imgs": [
      "assets/game/pieces/gem/gem_blue_06.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_blue_06.png"
     ],
     "color": null
    },
    {
     "value": 7,
     "imgs": [
      "assets/game/pieces/gem/gem_blue_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_blue_07.png"
     ],
     "color": null
    },
    {
     "value": 8,
     "imgs": [
      "assets/game/pieces/gem/gem_green_04.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_green_04.png"
     ],
     "color": null
    },
    {
     "value": 9,
     "imgs": [
      "assets/game/pieces/gem/gem_green_05.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_green_05.png"
     ],
     "color": null
    },
    {
     "value": 10,
     "imgs": [
      "assets/game/pieces/gem/gem_green_06.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_green_06.png"
     ],
     "color": null
    },
    {
     "value": 11,
     "imgs": [
      "assets/game/pieces/gem/gem_green_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_green_07.png"
     ],
     "color": null
    },
    {
     "value": 12,
     "imgs": [
      "assets/game/pieces/gem/gem_grey_04.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_grey_04.png"
     ],
     "color": null
    },
    {
     "value": 13,
     "imgs": [
      "assets/game/pieces/gem/gem_grey_05.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_grey_05.png"
     ],
     "color": null
    },
    {
     "value": 14,
     "imgs": [
      "assets/game/pieces/gem/gem_grey_06.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_grey_06.png"
     ],
     "color": null
    },
    {
     "value": 15,
     "imgs": [
      "assets/game/pieces/gem/gem_grey_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_grey_07.png"
     ],
     "color": null
    },
    {
     "value": 16,
     "imgs": [
      "assets/game/pieces/gem/gem_orange_04.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_orange_04.png"
     ],
     "color": null
    },
    {
     "value": 17,
     "imgs": [
      "assets/game/pieces/gem/gem_orange_05.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_orange_05.png"
     ],
     "color": null
    },
    {
     "value": 18,
     "imgs": [
      "assets/game/pieces/gem/gem_orange_06.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_orange_06.png"
     ],
     "color": null
    },
    {
     "value": 19,
     "imgs": [
      "assets/game/pieces/gem/gem_orange_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_orange_07.png"
     ],
     "color": null
    },
    {
     "value": 20,
     "imgs": [
      "assets/game/pieces/gem/gem_pink_04.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_pink_04.png"
     ],
     "color": null
    },
    {
     "value": 21,
     "imgs": [
      "assets/game/pieces/gem/gem_pink_05.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_pink_05.png"
     ],
     "color": null
    },
    {
     "value": 22,
     "imgs": [
      "assets/game/pieces/gem/gem_pink_06.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_pink_06.png"
     ],
     "color": null
    },
    {
     "value": 23,
     "imgs": [
      "assets/game/pieces/gem/gem_pink_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_pink_07.png"
     ],
     "color": null
    },
    {
     "value": 24,
     "imgs": [
      "assets/game/pieces/gem/gem_red_04.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_red_04.png"
     ],
     "color": null
    },
    {
     "value": 25,
     "imgs": [
      "assets/game/pieces/gem/gem_red_05.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_red_05.png"
     ],
     "color": null
    },
    {
     "value": 26,
     "imgs": [
      "assets/game/pieces/gem/gem_red_06.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_red_06.png"
     ],
     "color": null
    },
    {
     "value": 27,
     "imgs": [
      "assets/game/pieces/gem/gem_red_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_red_07.png"
     ],
     "color": null
    },
    {
     "value": 28,
     "imgs": [
      "assets/game/pieces/gem/gem_yellow_04.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_yellow_04.png"
     ],
     "color": null
    },
    {
     "value": 29,
     "imgs": [
      "assets/game/pieces/gem/gem_yellow_05.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_yellow_05.png"
     ],
     "color": null
    },
    {
     "value": 30,
     "imgs": [
      "assets/game/pieces/gem/gem_yellow_06.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_yellow_06.png"
     ],
     "color": null
    },
    {
     "value": 31,
     "imgs": [
      "assets/game/pieces/gem/gem_yellow_07.png"
     ],
     "timgs": [
      "assets/game/pieces/gem/gem_yellow_07.png"
     ],
     "color": null
    }
   ]
  }
 },
 "symbol": {
  "title": "Runes",
  "rules": [
   "symbol",
   "color",
   "opposite",
   "position"
  ],
  "pool": {
   "symbol": [
    {
     "value": "star",
     "imgs": [
      "assets/game/pieces/symbol/symbol_star.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_star.png"
     ],
     "color": "#e0393e",
     "tintable": true
    },
    {
     "value": "trophy",
     "imgs": [
      "assets/game/pieces/symbol/symbol_trophy.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_trophy.png"
     ],
     "color": "#2f7fe8",
     "tintable": true
    },
    {
     "value": "medal1",
     "imgs": [
      "assets/game/pieces/symbol/symbol_medal1.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_medal1.png"
     ],
     "color": "#4caf50",
     "tintable": true
    },
    {
     "value": "medal2",
     "imgs": [
      "assets/game/pieces/symbol/symbol_medal2.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_medal2.png"
     ],
     "color": "#f6c915",
     "tintable": true
    },
    {
     "value": "target",
     "imgs": [
      "assets/game/pieces/symbol/symbol_target.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_target.png"
     ],
     "color": "#8e5bd6",
     "tintable": true
    },
    {
     "value": "cross",
     "imgs": [
      "assets/game/pieces/symbol/symbol_cross.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_cross.png"
     ],
     "color": "#e26ab0",
     "tintable": true
    },
    {
     "value": "exclamation",
     "imgs": [
      "assets/game/pieces/symbol/symbol_exclamation.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_exclamation.png"
     ],
     "color": "#f28a1e",
     "tintable": true
    },
    {
     "value": "question",
     "imgs": [
      "assets/game/pieces/symbol/symbol_question.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_question.png"
     ],
     "color": "#8d6e63",
     "tintable": true
    },
    {
     "value": "checkmark",
     "imgs": [
      "assets/game/pieces/symbol/symbol_checkmark.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_checkmark.png"
     ],
     "color": "#e0393e",
     "tintable": true
    },
    {
     "value": "power",
     "imgs": [
      "assets/game/pieces/symbol/symbol_power.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_power.png"
     ],
     "color": "#2f7fe8",
     "tintable": true
    },
    {
     "value": "warning",
     "imgs": [
      "assets/game/pieces/symbol/symbol_warning.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_warning.png"
     ],
     "color": "#4caf50",
     "tintable": true
    },
    {
     "value": "plus",
     "imgs": [
      "assets/game/pieces/symbol/symbol_plus.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_plus.png"
     ],
     "color": "#f6c915",
     "tintable": true
    },
    {
     "value": "minus",
     "imgs": [
      "assets/game/pieces/symbol/symbol_minus.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_minus.png"
     ],
     "color": "#8e5bd6",
     "tintable": true
    },
    {
     "value": "gear",
     "imgs": [
      "assets/game/pieces/symbol/symbol_gear.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_gear.png"
     ],
     "color": "#e26ab0",
     "tintable": true
    },
    {
     "value": "arrowUp",
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowUp.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowUp.png"
     ],
     "color": "#f28a1e",
     "tintable": true
    },
    {
     "value": "arrowDown",
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowDown.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowDown.png"
     ],
     "color": "#8d6e63",
     "tintable": true
    },
    {
     "value": "arrowLeft",
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowLeft.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowLeft.png"
     ],
     "color": "#e0393e",
     "tintable": true
    },
    {
     "value": "arrowRight",
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowRight.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowRight.png"
     ],
     "color": "#2f7fe8",
     "tintable": true
    },
    {
     "value": "locked",
     "imgs": [
      "assets/game/pieces/symbol/symbol_locked.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_locked.png"
     ],
     "color": "#4caf50",
     "tintable": true
    },
    {
     "value": "unlocked",
     "imgs": [
      "assets/game/pieces/symbol/symbol_unlocked.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_unlocked.png"
     ],
     "color": "#f6c915",
     "tintable": true
    },
    {
     "value": "musicOn",
     "imgs": [
      "assets/game/pieces/symbol/symbol_musicOn.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_musicOn.png"
     ],
     "color": "#8e5bd6",
     "tintable": true
    },
    {
     "value": "musicOff",
     "imgs": [
      "assets/game/pieces/symbol/symbol_musicOff.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_musicOff.png"
     ],
     "color": "#e26ab0",
     "tintable": true
    }
   ],
   "color": [
    {
     "value": "red",
     "imgs": [
      "assets/game/pieces/symbol/symbol_star.png",
      "assets/game/pieces/symbol/symbol_checkmark.png",
      "assets/game/pieces/symbol/symbol_arrowLeft.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_star.png",
      "assets/game/pieces/symbol/symbol_checkmark.png",
      "assets/game/pieces/symbol/symbol_arrowLeft.png"
     ],
     "color": "#e0393e",
     "tintable": true
    },
    {
     "value": "blue",
     "imgs": [
      "assets/game/pieces/symbol/symbol_trophy.png",
      "assets/game/pieces/symbol/symbol_power.png",
      "assets/game/pieces/symbol/symbol_arrowRight.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_trophy.png",
      "assets/game/pieces/symbol/symbol_power.png",
      "assets/game/pieces/symbol/symbol_arrowRight.png"
     ],
     "color": "#2f7fe8",
     "tintable": true
    },
    {
     "value": "green",
     "imgs": [
      "assets/game/pieces/symbol/symbol_medal1.png",
      "assets/game/pieces/symbol/symbol_warning.png",
      "assets/game/pieces/symbol/symbol_locked.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_medal1.png",
      "assets/game/pieces/symbol/symbol_warning.png",
      "assets/game/pieces/symbol/symbol_locked.png"
     ],
     "color": "#4caf50",
     "tintable": true
    },
    {
     "value": "yellow",
     "imgs": [
      "assets/game/pieces/symbol/symbol_medal2.png",
      "assets/game/pieces/symbol/symbol_plus.png",
      "assets/game/pieces/symbol/symbol_unlocked.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_medal2.png",
      "assets/game/pieces/symbol/symbol_plus.png",
      "assets/game/pieces/symbol/symbol_unlocked.png"
     ],
     "color": "#f6c915",
     "tintable": true
    },
    {
     "value": "purple",
     "imgs": [
      "assets/game/pieces/symbol/symbol_target.png",
      "assets/game/pieces/symbol/symbol_minus.png",
      "assets/game/pieces/symbol/symbol_musicOn.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_target.png",
      "assets/game/pieces/symbol/symbol_minus.png",
      "assets/game/pieces/symbol/symbol_musicOn.png"
     ],
     "color": "#8e5bd6",
     "tintable": true
    },
    {
     "value": "pink",
     "imgs": [
      "assets/game/pieces/symbol/symbol_cross.png",
      "assets/game/pieces/symbol/symbol_gear.png",
      "assets/game/pieces/symbol/symbol_musicOff.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_cross.png",
      "assets/game/pieces/symbol/symbol_gear.png",
      "assets/game/pieces/symbol/symbol_musicOff.png"
     ],
     "color": "#e26ab0",
     "tintable": true
    },
    {
     "value": "orange",
     "imgs": [
      "assets/game/pieces/symbol/symbol_exclamation.png",
      "assets/game/pieces/symbol/symbol_arrowUp.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_exclamation.png",
      "assets/game/pieces/symbol/symbol_arrowUp.png"
     ],
     "color": "#f28a1e",
     "tintable": true
    },
    {
     "value": "brown",
     "imgs": [
      "assets/game/pieces/symbol/symbol_question.png",
      "assets/game/pieces/symbol/symbol_arrowDown.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_question.png",
      "assets/game/pieces/symbol/symbol_arrowDown.png"
     ],
     "color": "#8d6e63",
     "tintable": true
    }
   ],
   "opposite": [
    {
     "value": "pair0",
     "imgs": [
      "assets/game/pieces/symbol/symbol_plus.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_minus.png"
     ],
     "color": "#e0393e",
     "tintable": true,
     "pair": {
      "a": "plus",
      "b": "minus"
     }
    },
    {
     "value": "pair1",
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowUp.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowDown.png"
     ],
     "color": "#2f7fe8",
     "tintable": true,
     "pair": {
      "a": "arrowUp",
      "b": "arrowDown"
     }
    },
    {
     "value": "pair2",
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowLeft.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowRight.png"
     ],
     "color": "#4caf50",
     "tintable": true,
     "pair": {
      "a": "arrowLeft",
      "b": "arrowRight"
     }
    },
    {
     "value": "pair3",
     "imgs": [
      "assets/game/pieces/symbol/symbol_locked.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_unlocked.png"
     ],
     "color": "#f6c915",
     "tintable": true,
     "pair": {
      "a": "locked",
      "b": "unlocked"
     }
    },
    {
     "value": "pair4",
     "imgs": [
      "assets/game/pieces/symbol/symbol_musicOn.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_musicOff.png"
     ],
     "color": "#8e5bd6",
     "tintable": true,
     "pair": {
      "a": "musicOn",
      "b": "musicOff"
     }
    },
    {
     "value": "pair5",
     "imgs": [
      "assets/game/pieces/symbol/symbol_cross.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_checkmark.png"
     ],
     "color": "#e26ab0",
     "tintable": true,
     "pair": {
      "a": "cross",
      "b": "checkmark"
     }
    }
   ],
   "position": [
    {
     "value": 0,
     "imgs": [
      "assets/game/pieces/symbol/symbol_star.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_star.png"
     ],
     "color": "#e0393e",
     "tintable": true
    },
    {
     "value": 1,
     "imgs": [
      "assets/game/pieces/symbol/symbol_trophy.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_trophy.png"
     ],
     "color": "#2f7fe8",
     "tintable": true
    },
    {
     "value": 2,
     "imgs": [
      "assets/game/pieces/symbol/symbol_medal1.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_medal1.png"
     ],
     "color": "#4caf50",
     "tintable": true
    },
    {
     "value": 3,
     "imgs": [
      "assets/game/pieces/symbol/symbol_medal2.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_medal2.png"
     ],
     "color": "#f6c915",
     "tintable": true
    },
    {
     "value": 4,
     "imgs": [
      "assets/game/pieces/symbol/symbol_target.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_target.png"
     ],
     "color": "#8e5bd6",
     "tintable": true
    },
    {
     "value": 5,
     "imgs": [
      "assets/game/pieces/symbol/symbol_cross.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_cross.png"
     ],
     "color": "#e26ab0",
     "tintable": true
    },
    {
     "value": 6,
     "imgs": [
      "assets/game/pieces/symbol/symbol_exclamation.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_exclamation.png"
     ],
     "color": "#f28a1e",
     "tintable": true
    },
    {
     "value": 7,
     "imgs": [
      "assets/game/pieces/symbol/symbol_question.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_question.png"
     ],
     "color": "#8d6e63",
     "tintable": true
    },
    {
     "value": 8,
     "imgs": [
      "assets/game/pieces/symbol/symbol_checkmark.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_checkmark.png"
     ],
     "color": "#e0393e",
     "tintable": true
    },
    {
     "value": 9,
     "imgs": [
      "assets/game/pieces/symbol/symbol_power.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_power.png"
     ],
     "color": "#2f7fe8",
     "tintable": true
    },
    {
     "value": 10,
     "imgs": [
      "assets/game/pieces/symbol/symbol_warning.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_warning.png"
     ],
     "color": "#4caf50",
     "tintable": true
    },
    {
     "value": 11,
     "imgs": [
      "assets/game/pieces/symbol/symbol_plus.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_plus.png"
     ],
     "color": "#f6c915",
     "tintable": true
    },
    {
     "value": 12,
     "imgs": [
      "assets/game/pieces/symbol/symbol_minus.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_minus.png"
     ],
     "color": "#8e5bd6",
     "tintable": true
    },
    {
     "value": 13,
     "imgs": [
      "assets/game/pieces/symbol/symbol_gear.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_gear.png"
     ],
     "color": "#e26ab0",
     "tintable": true
    },
    {
     "value": 14,
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowUp.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowUp.png"
     ],
     "color": "#f28a1e",
     "tintable": true
    },
    {
     "value": 15,
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowDown.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowDown.png"
     ],
     "color": "#8d6e63",
     "tintable": true
    },
    {
     "value": 16,
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowLeft.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowLeft.png"
     ],
     "color": "#e0393e",
     "tintable": true
    },
    {
     "value": 17,
     "imgs": [
      "assets/game/pieces/symbol/symbol_arrowRight.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_arrowRight.png"
     ],
     "color": "#2f7fe8",
     "tintable": true
    },
    {
     "value": 18,
     "imgs": [
      "assets/game/pieces/symbol/symbol_locked.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_locked.png"
     ],
     "color": "#4caf50",
     "tintable": true
    },
    {
     "value": 19,
     "imgs": [
      "assets/game/pieces/symbol/symbol_unlocked.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_unlocked.png"
     ],
     "color": "#f6c915",
     "tintable": true
    },
    {
     "value": 20,
     "imgs": [
      "assets/game/pieces/symbol/symbol_musicOn.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_musicOn.png"
     ],
     "color": "#8e5bd6",
     "tintable": true
    },
    {
     "value": 21,
     "imgs": [
      "assets/game/pieces/symbol/symbol_musicOff.png"
     ],
     "timgs": [
      "assets/game/pieces/symbol/symbol_musicOff.png"
     ],
     "color": "#e26ab0",
     "tintable": true
    }
   ]
  }
 },
 "domino": {
  "title": "Dominoes",
  "rules": [
   "number",
   "motif",
   "position"
  ],
  "pool": {
   "number": [
    {
     "value": 0,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_0_0.png",
      "assets/game/pieces/domino/domino_hearts_0_0.png",
      "assets/game/pieces/domino/domino_gingerbread_0_0.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_0_0.png",
      "assets/game/pieces/domino/domino_hearts_0_0.png",
      "assets/game/pieces/domino/domino_gingerbread_0_0.png"
     ],
     "color": null,
     "number": 0
    },
    {
     "value": 1,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_0_1.png",
      "assets/game/pieces/domino/domino_hearts_0_1.png",
      "assets/game/pieces/domino/domino_gingerbread_0_1.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_0_1.png",
      "assets/game/pieces/domino/domino_hearts_0_1.png",
      "assets/game/pieces/domino/domino_gingerbread_0_1.png"
     ],
     "color": null,
     "number": 1
    },
    {
     "value": 2,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_0_2.png",
      "assets/game/pieces/domino/domino_hearts_0_2.png",
      "assets/game/pieces/domino/domino_gingerbread_0_2.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_0_2.png",
      "assets/game/pieces/domino/domino_hearts_0_2.png",
      "assets/game/pieces/domino/domino_gingerbread_0_2.png"
     ],
     "color": null,
     "number": 2
    },
    {
     "value": 3,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_0_3.png",
      "assets/game/pieces/domino/domino_hearts_0_3.png",
      "assets/game/pieces/domino/domino_gingerbread_0_3.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_0_3.png",
      "assets/game/pieces/domino/domino_hearts_0_3.png",
      "assets/game/pieces/domino/domino_gingerbread_0_3.png"
     ],
     "color": null,
     "number": 3
    },
    {
     "value": 4,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_1_3.png",
      "assets/game/pieces/domino/domino_hearts_1_3.png",
      "assets/game/pieces/domino/domino_gingerbread_1_3.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_1_3.png",
      "assets/game/pieces/domino/domino_hearts_1_3.png",
      "assets/game/pieces/domino/domino_gingerbread_1_3.png"
     ],
     "color": null,
     "number": 4
    },
    {
     "value": 5,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_1_4.png",
      "assets/game/pieces/domino/domino_hearts_1_4.png",
      "assets/game/pieces/domino/domino_gingerbread_1_4.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_1_4.png",
      "assets/game/pieces/domino/domino_hearts_1_4.png",
      "assets/game/pieces/domino/domino_gingerbread_1_4.png"
     ],
     "color": null,
     "number": 5
    },
    {
     "value": 6,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_2_4.png",
      "assets/game/pieces/domino/domino_hearts_2_4.png",
      "assets/game/pieces/domino/domino_gingerbread_2_4.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_2_4.png",
      "assets/game/pieces/domino/domino_hearts_2_4.png",
      "assets/game/pieces/domino/domino_gingerbread_2_4.png"
     ],
     "color": null,
     "number": 6
    },
    {
     "value": 7,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_2_5.png",
      "assets/game/pieces/domino/domino_hearts_2_5.png",
      "assets/game/pieces/domino/domino_gingerbread_2_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_2_5.png",
      "assets/game/pieces/domino/domino_hearts_2_5.png",
      "assets/game/pieces/domino/domino_gingerbread_2_5.png"
     ],
     "color": null,
     "number": 7
    },
    {
     "value": 8,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_3_5.png",
      "assets/game/pieces/domino/domino_hearts_3_5.png",
      "assets/game/pieces/domino/domino_gingerbread_3_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_3_5.png",
      "assets/game/pieces/domino/domino_hearts_3_5.png",
      "assets/game/pieces/domino/domino_gingerbread_3_5.png"
     ],
     "color": null,
     "number": 8
    }
   ],
   "motif": [
    {
     "value": "gingerbread",
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_0.png",
      "assets/game/pieces/domino/domino_gingerbread_0_1.png",
      "assets/game/pieces/domino/domino_gingerbread_0_2.png",
      "assets/game/pieces/domino/domino_gingerbread_0_3.png",
      "assets/game/pieces/domino/domino_gingerbread_1_3.png",
      "assets/game/pieces/domino/domino_gingerbread_1_4.png",
      "assets/game/pieces/domino/domino_gingerbread_2_4.png",
      "assets/game/pieces/domino/domino_gingerbread_2_5.png",
      "assets/game/pieces/domino/domino_gingerbread_3_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_0.png",
      "assets/game/pieces/domino/domino_gingerbread_0_1.png",
      "assets/game/pieces/domino/domino_gingerbread_0_2.png",
      "assets/game/pieces/domino/domino_gingerbread_0_3.png",
      "assets/game/pieces/domino/domino_gingerbread_1_3.png",
      "assets/game/pieces/domino/domino_gingerbread_1_4.png",
      "assets/game/pieces/domino/domino_gingerbread_2_4.png",
      "assets/game/pieces/domino/domino_gingerbread_2_5.png",
      "assets/game/pieces/domino/domino_gingerbread_3_5.png"
     ],
     "color": null,
     "motif": "gingerbread"
    },
    {
     "value": "hearts",
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_0_0.png",
      "assets/game/pieces/domino/domino_hearts_0_1.png",
      "assets/game/pieces/domino/domino_hearts_0_2.png",
      "assets/game/pieces/domino/domino_hearts_0_3.png",
      "assets/game/pieces/domino/domino_hearts_1_3.png",
      "assets/game/pieces/domino/domino_hearts_1_4.png",
      "assets/game/pieces/domino/domino_hearts_2_4.png",
      "assets/game/pieces/domino/domino_hearts_2_5.png",
      "assets/game/pieces/domino/domino_hearts_3_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_0_0.png",
      "assets/game/pieces/domino/domino_hearts_0_1.png",
      "assets/game/pieces/domino/domino_hearts_0_2.png",
      "assets/game/pieces/domino/domino_hearts_0_3.png",
      "assets/game/pieces/domino/domino_hearts_1_3.png",
      "assets/game/pieces/domino/domino_hearts_1_4.png",
      "assets/game/pieces/domino/domino_hearts_2_4.png",
      "assets/game/pieces/domino/domino_hearts_2_5.png",
      "assets/game/pieces/domino/domino_hearts_3_5.png"
     ],
     "color": null,
     "motif": "hearts"
    },
    {
     "value": "stars",
     "imgs": [
      "assets/game/pieces/domino/domino_stars_0_0.png",
      "assets/game/pieces/domino/domino_stars_0_1.png",
      "assets/game/pieces/domino/domino_stars_0_2.png",
      "assets/game/pieces/domino/domino_stars_0_3.png",
      "assets/game/pieces/domino/domino_stars_1_3.png",
      "assets/game/pieces/domino/domino_stars_1_4.png",
      "assets/game/pieces/domino/domino_stars_2_4.png",
      "assets/game/pieces/domino/domino_stars_2_5.png",
      "assets/game/pieces/domino/domino_stars_3_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_0_0.png",
      "assets/game/pieces/domino/domino_stars_0_1.png",
      "assets/game/pieces/domino/domino_stars_0_2.png",
      "assets/game/pieces/domino/domino_stars_0_3.png",
      "assets/game/pieces/domino/domino_stars_1_3.png",
      "assets/game/pieces/domino/domino_stars_1_4.png",
      "assets/game/pieces/domino/domino_stars_2_4.png",
      "assets/game/pieces/domino/domino_stars_2_5.png",
      "assets/game/pieces/domino/domino_stars_3_5.png"
     ],
     "color": null,
     "motif": "stars"
    }
   ],
   "position": [
    {
     "value": 0,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_0_0.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_0_0.png"
     ],
     "color": null
    },
    {
     "value": 1,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_0_1.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_0_1.png"
     ],
     "color": null
    },
    {
     "value": 2,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_0_2.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_0_2.png"
     ],
     "color": null
    },
    {
     "value": 3,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_0_3.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_0_3.png"
     ],
     "color": null
    },
    {
     "value": 4,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_1_3.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_1_3.png"
     ],
     "color": null
    },
    {
     "value": 5,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_1_4.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_1_4.png"
     ],
     "color": null
    },
    {
     "value": 6,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_2_4.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_2_4.png"
     ],
     "color": null
    },
    {
     "value": 7,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_2_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_2_5.png"
     ],
     "color": null
    },
    {
     "value": 8,
     "imgs": [
      "assets/game/pieces/domino/domino_stars_3_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_stars_3_5.png"
     ],
     "color": null
    },
    {
     "value": 9,
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_0_0.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_0_0.png"
     ],
     "color": null
    },
    {
     "value": 10,
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_0_1.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_0_1.png"
     ],
     "color": null
    },
    {
     "value": 11,
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_0_2.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_0_2.png"
     ],
     "color": null
    },
    {
     "value": 12,
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_0_3.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_0_3.png"
     ],
     "color": null
    },
    {
     "value": 13,
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_1_3.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_1_3.png"
     ],
     "color": null
    },
    {
     "value": 14,
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_1_4.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_1_4.png"
     ],
     "color": null
    },
    {
     "value": 15,
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_2_4.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_2_4.png"
     ],
     "color": null
    },
    {
     "value": 16,
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_2_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_2_5.png"
     ],
     "color": null
    },
    {
     "value": 17,
     "imgs": [
      "assets/game/pieces/domino/domino_hearts_3_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_hearts_3_5.png"
     ],
     "color": null
    },
    {
     "value": 18,
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_0.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_0.png"
     ],
     "color": null
    },
    {
     "value": 19,
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_1.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_1.png"
     ],
     "color": null
    },
    {
     "value": 20,
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_2.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_2.png"
     ],
     "color": null
    },
    {
     "value": 21,
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_3.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_0_3.png"
     ],
     "color": null
    },
    {
     "value": 22,
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_1_3.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_1_3.png"
     ],
     "color": null
    },
    {
     "value": 23,
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_1_4.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_1_4.png"
     ],
     "color": null
    },
    {
     "value": 24,
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_2_4.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_2_4.png"
     ],
     "color": null
    },
    {
     "value": 25,
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_2_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_2_5.png"
     ],
     "color": null
    },
    {
     "value": 26,
     "imgs": [
      "assets/game/pieces/domino/domino_gingerbread_3_5.png"
     ],
     "timgs": [
      "assets/game/pieces/domino/domino_gingerbread_3_5.png"
     ],
     "color": null
    }
   ]
  }
 }
};
const RULES_DATA = {
 "element": {
  "title": "Elemental",
  "desc": "same element badge"
 },
 "color": {
  "title": "Rainbow Riddle",
  "desc": "same color ring"
 },
 "type": {
  "title": "Species Match",
  "desc": "same kind of thing"
 },
 "symbol": {
  "title": "Symbology",
  "desc": "same rune shape"
 },
 "opposite": {
  "title": "Opposites Attract",
  "desc": "opposite runes pair up"
 },
 "number": {
  "title": "Domino Theory",
  "desc": "same pip total"
 },
 "motif": {
  "title": "Pattern Play",
  "desc": "same pip style"
 },
 "position": {
  "title": "Order of Operations",
  "desc": "same position in line"
 }
};
const COLOR_HEX = {
 "red": "#e0393e",
 "orange": "#f28a1e",
 "yellow": "#f6c915",
 "green": "#4caf50",
 "blue": "#2f7fe8",
 "purple": "#8e5bd6",
 "pink": "#e26ab0",
 "brown": "#8d6e63"
};